### ISSUE TITLE
Adding Support for Enumeratum ValueEnums

### ISSUE THREAD

**Issue by ChrisMcD1** [valentiay/phobos#27]
Hello!

I've been trying out Phobos and really liking it so far. I noticed there was not support for enumeratum's ValueEnum.

I've written up a version of these locally, would you be interested in me creating a PR?

**Comment by ChrisMcD1** [comment]
I went ahead and made https://github.com/valentiay/phobos/pull/28 to let you see what my implementation looks like.

**Comment by valentiay** [comment]
Resolved in #28, published in `0.24.0`
