### ISSUE TITLE
Ignore namespace

### ISSUE THREAD

**Issue by iyfedorov** [valentiay/phobos#3]
Hello! How i can ignore unnecessary namespaces? 

`phobos.decoding.DecodingError: Error while decoding XML: Invalid namespace. Expected no namespace, but found '******'`

**Comment by valentiay** [comment]
Hi!
Currently there's no such feature, but it looks like a setting that can be added to [ElementCodecConfig](https://github.com/valentiay/phobos/blob/master/modules/core/src/main/scala/phobos/configured/ElementCodecConfig.scala). I'm not 100% sure yet, but I'll take a closer look and try to implement it this weekend

**Comment by valentiay** [comment]
Fixed in #5 and published in [`0.22.0`](https://github.com/valentiay/phobos/releases/tag/0.22.0). Thanks again for your contribution!
